### ISSUE TITLE
Plugin not displaying?

### ISSUE THREAD

**Issue by Intecpsp** [Varietyz/literegenmeter#1] opened 2024-10-12 02:34 UTC
I just got this plugin and I see that it disables a few of my current plugins, which is fine, but this plugin doesn't appear to be displaying anywhere with default settings.

**Comment by Intecpsp** [comment] 2024-10-12 02:42
Ah, I see the status bars are hidden by default (maybe not hidden by default?). But always showing them seems to be messed up with the resizable modern layout
![Screenshot 2024-10-11 at 10 41 55 PM](https://github.com/user-attachments/assets/e7304ff1-f829-41e0-89a5-1fbff96844d6)

**Comment by Varietyz** [comment] 2024-10-12 09:31
> Ah, I see the status bars are hidden by default (maybe not hidden by default?). But always showing them seems to be messed up with the resizable modern layout ![Screenshot 2024-10-11 at 10 41 55 PM](https://private-user-images.githubusercontent.com/1164012/375917936-e7304ff1-f829-41e0-89a5-1fbff96844d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjU3MzcsIm5iZiI6MTcyODcyNTQzNywicGF0aCI6Ii8xMTY0MDEyLzM3NTkxNzkzNi1lNzMwNGZmMS1mODI5LTQxZTAtODlhNS0xZmJmZjk2ODQ0ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTJUMDkzMDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTlkNjkwNGM5MDkzZWMzOWE2MTgwNzY4NWI3ZDhmYmMxMmUwMGIzMzQyMGY0MjhmODM5NWU1MmNmN2NiNDk4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.u0xQst9H9AJmW7-n_9_YMhA_sxN5iyPP9QEgAadkU24)

i just noticed this too, upon my latest change, i probably forgot a specification for that config!
i'm going to solve it today and submit the update. Apologies for the mishap here!

**Comment by Varietyz** [comment] 2024-10-12 10:37
FIX for it is awaiting approval.
[ISSUE FIX - LITE REGEN METER](https://github.com/runelite/plugin-hub/pull/6756)

**Comment by Varietyz** [comment] 2024-10-12 13:15
ISSUE FIXED ON THE HUB!!

**Closed by Varietyz** 2024-10-12 13:15 UTC

**Comment by Intecpsp** [comment] 2024-10-12 17:18
I think this broke the Vanilla theme

**Comment by Varietyz** [comment] 2024-10-12 18:13
> I think this broke the Vanilla theme

What do you mean?
Got a screenshot or information to what it is your referring to?

**Comment by Intecpsp** [comment] 2024-10-12 18:17
Sorry, I should've been more descriptive. When flipping between the `Vanilla` and `RuneLITE` themes, the status bars are not changing as they did before this past update.

**Comment by Varietyz** [comment] 2024-10-13 08:56
> Sorry, I should've been more descriptive. When flipping between the `Vanilla` and `RuneLITE` themes, the status bars are not changing as they did before this past update.

Im trying to find the issue, but everything seems to be working as intended. The Status bars match the RuneLITE theme and also for the Vanilla theme.

If you could be including a screenshot of the issue your running into, i might be able to have more insight on whats going wrong.

When you flip to RuneLITE, and your on a theme pack that is different. The stat bars and regen meters will not match. It only fits for the RuneLITE theme.

so placement should be different for vanilla and runelite theme

**Comment by Varietyz** [comment] 2024-10-14 19:00
> Here is a screen recording of me flipping back and forth with no changes to the stat bars
> 
>  Screen.Recording.2024-10-14.at.8.10.49.AM.mov

Yes, that is because the RuneLITE theme and the Vanilla theme have the same aspect ratio.

You are in Modern Resize, go to fixed classic to see stat bar changes.

![Changes](https://github.com/user-attachments/assets/883b0278-c0e4-42be-ad6d-3216541f5faa)

In an upcomming update, resize will have 3 new options
![image](https://github.com/user-attachments/assets/fffd073c-4b64-4adc-905e-adb21c0087f3)
![image](https://github.com/user-attachments/assets/7ecc07ea-a060-4e9e-a081-cb0ac9429039)
![image](https://github.com/user-attachments/assets/8d3d4fed-0ddb-43f1-95ff-f09ed7eeaa9f)

**Comment by Intecpsp** [comment] 2024-10-14 19:51
Can modern resizeable not get the vanilla theme? I want to have the numerics, but 100+ go outside of the frames

**Comment by Varietyz** [comment] 2024-10-15 08:32
> Can modern resizeable not get the vanilla theme? I want to have the numerics, but 100+ go outside of the frames

Just change the width of your bars in resize mode.
![image](https://github.com/user-attachments/assets/13820e02-da5a-4b2b-bca2-08767ebd8181) ![image](https://github.com/user-attachments/assets/adf2ec1f-6608-4fe5-a1c4-edb7459206f2)


The issue you're facing is due to your own configuration setup.
It's not code related.
